steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "server", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "server:latest", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "$PROJECT_ID",
        "--image",
        "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--quiet",
      ]
    env:
      - "PORT=8080"
      - "TELEGRAM_TOKEN=${_TELEGRAM_TOKEN}"
      - "TELEGRAM_CHAT_ID=${_TELEGRAM_CHAT_ID}"
images: ["gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"]
