version: "3.3"
services:
  server:
    build: ./server/
    image: server:latest
    hostname: ${HOSTNAME}
    depends_on:
      - client
    ports:
      - ${IP_ADDRESS}:${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - clientbuild:/usr/client/dist
    environment:
      - STATICFILE_DIRECTORY=/usr/client/dist
      - PORT=${SERVER_PORT}

  client:
    build: ./client/
    image: client:latest
    command: yarn build
    volumes:
      - clientbuild:/usr/client/dist

volumes:
  clientbuild:
